# Generated by Django 5.1.4 on 2025-04-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpeningDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Lunes", "Lunes"),
                            ("Martes", "Martes"),
                            ("Miercoles", "Miércoles"),
                            ("Jueves", "Jueves"),
                            ("Viernes", "Viernes"),
                            ("Sabado", "Sábado"),
                            ("Domingo", "Domingo"),
                        ],
                        max_length=9,
                        unique=True,
                    ),
                ),
                (
                    "state_day",
                    models.CharField(
                        choices=[("Abierto", "Abierto"), ("Cerrado", "Cerrado")],
                        max_length=7,
                    ),
                ),
                ("hour_start", models.TimeField(null=True)),
                ("hour_end", models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                ("duration", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Peluqueria", "Peluquería"),
                            ("Estetica", "Estética"),
                            ("Tratamientos", "Tratamientos"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
