# Generated by Django 5.1.4 on 2025-04-23 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_cl", models.EmailField(max_length=254)),
                ("name_cl", models.CharField(max_length=30)),
                (
                    "phone_number_cl",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="The phone number must begin with: '+34' and include 9 more digits.",
                                regex="^\\+34?3?\\d{9}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=30)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="The phone number must begin with: '+34' and include 9 more digits.",
                                regex="^\\+34?3?\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="service_employee", to="settingssalon.services"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Absences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ab", models.DateField()),
                ("hour_start_ab", models.TimeField()),
                ("hour_end_ab", models.TimeField()),
                ("reason", models.CharField(max_length=200)),
                (
                    "employee_ab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_absence",
                        to="settingssalon.employees",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Lunes", "Lunes"),
                            ("Martes", "Martes"),
                            ("Miercoles", "Miércoles"),
                            ("Jueves", "Jueves"),
                            ("Viernes", "Viernes"),
                            ("Sabado", "Sábado"),
                            ("Domingo", "Domingo"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "state_day",
                    models.CharField(
                        choices=[("Trabajo", "Trabajo"), ("Descanso", "Descanso")],
                        max_length=8,
                    ),
                ),
                ("hour_start_sc", models.TimeField(null=True)),
                ("hour_end_sc", models.TimeField(null=True)),
                (
                    "employee_sc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_schedule",
                        to="settingssalon.employees",
                    ),
                ),
            ],
        ),
    ]
