# Generated by Django 5.1.4 on 2025-04-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0002_clients_employees_absences_schedules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingdays",
            name="day",
            field=models.CharField(
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                ],
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="day",
            field=models.CharField(
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                ],
                max_length=9,
            ),
        ),
    ]
