# Generated by Django 5.1.4 on 2025-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0003_alter_openingdays_day_alter_schedules_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingdays",
            name="day",
            field=models.CharField(
                choices=[
                    ("lunes", "Lunes"),
                    ("martes", "Martes"),
                    ("miércoles", "Miércoles"),
                    ("jueves", "Jueves"),
                    ("viernes", "Viernes"),
                    ("sábado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="openingdays",
            name="state_day",
            field=models.CharField(
                choices=[("abierto", "Abierto"), ("cerrado", "Cerrado")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="day",
            field=models.CharField(
                choices=[
                    ("lunes", "Lunes"),
                    ("martes", "Martes"),
                    ("miércoles", "Miércoles"),
                    ("jueves", "Jueves"),
                    ("viernes", "Viernes"),
                    ("sábado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="state_day",
            field=models.CharField(
                choices=[("trabajo", "Trabajo"), ("descanso", "Descanso")], max_length=8
            ),
        ),
    ]
