# Generated by Django 5.1.4 on 2025-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settingssalon",
            "0004_alter_openingdays_day_alter_openingdays_state_day_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingdays",
            name="day",
            field=models.CharField(
                choices=[
                    ("lunes", "Lunes"),
                    ("martes", "Martes"),
                    ("miércoles", "Miércoles"),
                    ("jueves", "Jueves"),
                    ("viernes", "Viernes"),
                    ("sábado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=9,
            ),
        ),
    ]
