# Generated by Django 5.1.4 on 2025-04-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0005_alter_openingdays_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingdays",
            name="day",
            field=models.CharField(
                choices=[
                    ("lunes", "Lunes"),
                    ("martes", "Martes"),
                    ("miércoles", "Miércoles"),
                    ("jueves", "Jueves"),
                    ("viernes", "Viernes"),
                    ("sábado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=9,
                unique=True,
            ),
        ),
    ]
