# Generated by Django 5.1.4 on 2025-04-23 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0006_alter_openingdays_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_dt", models.DateField()),
                ("hour_dt", models.TimeField()),
                (
                    "client_dt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_date",
                        to="settingssalon.clients",
                    ),
                ),
                (
                    "employee_dt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_date",
                        to="settingssalon.employees",
                    ),
                ),
                (
                    "service_dt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_date",
                        to="settingssalon.services",
                    ),
                ),
            ],
        ),
    ]
