# Generated by Django 5.1.4 on 2025-04-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0007_dates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="absences", old_name="reason", new_name="reason_ab",
        ),
        migrations.RenameField(
            model_name="employees", old_name="email", new_name="email_empl",
        ),
        migrations.RenameField(
            model_name="employees", old_name="name", new_name="name_empl",
        ),
        migrations.RenameField(
            model_name="employees",
            old_name="phone_number",
            new_name="phone_number_empl",
        ),
        migrations.RenameField(
            model_name="employees", old_name="services", new_name="services_empl",
        ),
        migrations.RenameField(
            model_name="schedules", old_name="day", new_name="day_sc",
        ),
        migrations.RenameField(
            model_name="schedules", old_name="state_day", new_name="state_day_sc",
        ),
        migrations.RenameField(
            model_name="services", old_name="category", new_name="category_sr",
        ),
        migrations.RenameField(
            model_name="services", old_name="description", new_name="description_sr",
        ),
        migrations.RenameField(
            model_name="services", old_name="duration", new_name="duration_sr",
        ),
        migrations.RenameField(
            model_name="services", old_name="price", new_name="price_sr",
        ),
        migrations.RenameField(
            model_name="services", old_name="service", new_name="service_sr",
        ),
    ]
