# Generated by Django 5.1.4 on 2025-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0008_rename_reason_absences_reason_ab_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dates", old_name="hour_dt", new_name="hour_start_dt",
        ),
        migrations.AddField(
            model_name="dates",
            name="hour_end_dt",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
