# Generated by Django 5.1.4 on 2025-04-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0009_rename_hour_dt_dates_hour_start_dt_dates_hour_end_dt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dates", old_name="hour_start_dt", new_name="hour_dt",
        ),
        migrations.RemoveField(model_name="dates", name="hour_end_dt",),
    ]
