# Generated by Django 5.1.4 on 2025-04-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0010_rename_hour_start_dt_dates_hour_dt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dates", old_name="hour_dt", new_name="hour_start_dt",
        ),
        migrations.AddField(
            model_name="dates", name="hour_end_dt", field=models.TimeField(null=True),
        ),
    ]
