# Generated by Django 4.2.17 on 2025-04-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0011_rename_hour_dt_dates_hour_start_dt_dates_hour_end_dt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingdays",
            name="day",
            field=models.CharField(
                choices=[
                    ("Lunes", "lunes"),
                    ("Martes", "martes"),
                    ("Miércoles", "miércoles"),
                    ("Jueves", "jueves"),
                    ("Viernes", "viernes"),
                    ("Sábado", "sábado"),
                    ("Domingo", "domingo"),
                ],
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="openingdays",
            name="state_day",
            field=models.CharField(
                choices=[("Abierto", "abierto"), ("Cerrado", "cerrado")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="day_sc",
            field=models.CharField(
                choices=[
                    ("Lunes", "lunes"),
                    ("Martes", "martes"),
                    ("Miércoles", "miércoles"),
                    ("Jueves", "jueves"),
                    ("Viernes", "viernes"),
                    ("Sábado", "sábado"),
                    ("Domingo", "domingo"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="state_day_sc",
            field=models.CharField(
                choices=[("Descanso", "descanso"), ("Trabajo", "trabajo")], max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="category_sr",
            field=models.CharField(
                choices=[
                    ("Peluquería", "Peluqueria"),
                    ("Estética", "Estetica"),
                    ("Tratamientos", "Tratamientos"),
                ],
                max_length=12,
            ),
        ),
    ]
