# Generated by Django 4.2.17 on 2025-04-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "settingssalon",
            "0012_alter_openingdays_day_alter_openingdays_state_day_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="dates", name="hour_end_dt",),
    ]
