# Generated by Django 4.2.17 on 2025-04-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0013_remove_dates_hour_end_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="dates",
            name="hour_end_dt",
            field=models.TimeField(default="0:00", editable=False),
            preserve_default=False,
        ),
    ]
