# Generated by Django 5.1.4 on 2025-04-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0014_dates_hour_end_dt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="absences", old_name="date_ab", new_name="date",
        ),
        migrations.RenameField(
            model_name="absences", old_name="employee_ab", new_name="employee",
        ),
        migrations.RenameField(
            model_name="absences", old_name="hour_end_ab", new_name="hour_end",
        ),
        migrations.RenameField(
            model_name="absences", old_name="hour_start_ab", new_name="hour_start",
        ),
        migrations.RenameField(
            model_name="absences", old_name="reason_ab", new_name="reason",
        ),
        migrations.RenameField(
            model_name="clients", old_name="email_cl", new_name="email",
        ),
        migrations.RenameField(
            model_name="clients", old_name="name_cl", new_name="name",
        ),
        migrations.RenameField(
            model_name="clients", old_name="phone_number_cl", new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="dates", old_name="client_dt", new_name="client",
        ),
        migrations.RenameField(
            model_name="dates", old_name="date_dt", new_name="date",
        ),
        migrations.RenameField(
            model_name="dates", old_name="employee_dt", new_name="employee",
        ),
        migrations.RenameField(
            model_name="dates", old_name="hour_end_dt", new_name="hour_end",
        ),
        migrations.RenameField(
            model_name="dates", old_name="hour_start_dt", new_name="hour_start",
        ),
        migrations.RenameField(
            model_name="dates", old_name="service_dt", new_name="service",
        ),
        migrations.RenameField(
            model_name="employees", old_name="email_empl", new_name="email",
        ),
        migrations.RenameField(
            model_name="employees", old_name="name_empl", new_name="name",
        ),
        migrations.RenameField(
            model_name="employees",
            old_name="phone_number_empl",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="employees", old_name="services_empl", new_name="services",
        ),
        migrations.RenameField(
            model_name="schedules", old_name="day_sc", new_name="day",
        ),
        migrations.RenameField(
            model_name="schedules", old_name="employee_sc", new_name="employee",
        ),
        migrations.RenameField(
            model_name="schedules", old_name="hour_end_sc", new_name="hour_end",
        ),
        migrations.RenameField(
            model_name="schedules", old_name="hour_start_sc", new_name="hour_start",
        ),
        migrations.RenameField(
            model_name="schedules", old_name="state_day_sc", new_name="state_day",
        ),
        migrations.RenameField(
            model_name="services", old_name="category_sr", new_name="category",
        ),
        migrations.RenameField(
            model_name="services", old_name="description_sr", new_name="description",
        ),
        migrations.RenameField(
            model_name="services", old_name="duration_sr", new_name="duration",
        ),
        migrations.RenameField(
            model_name="services", old_name="price_sr", new_name="price",
        ),
        migrations.RenameField(
            model_name="services", old_name="service_sr", new_name="service",
        ),
    ]
