# Generated by Django 5.1.4 on 2025-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0015_rename_date_ab_absences_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services", name="duration", field=models.DurationField(),
        ),
    ]
