# Generated by Django 5.1.4 on 2025-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0016_alter_services_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services", name="duration", field=models.TimeField(),
        ),
    ]
