# Generated by Django 5.1.4 on 2025-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingssalon", "0017_alter_services_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingdays",
            name="day",
            field=models.CharField(
                choices=[
                    ("lunes", "Lunes"),
                    ("martes", "Martes"),
                    ("miércoles", "Miércoles"),
                    ("jueves", "Jueves"),
                    ("viernes", "Viernes"),
                    ("sábado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="openingdays",
            name="state_day",
            field=models.CharField(
                choices=[("abierto", "Abierto"), ("cerrado", "Cerrado")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="day",
            field=models.CharField(
                choices=[
                    ("lunes", "Lunes"),
                    ("martes", "Martes"),
                    ("miércoles", "Miércoles"),
                    ("jueves", "Jueves"),
                    ("viernes", "Viernes"),
                    ("sábado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="schedules",
            name="state_day",
            field=models.CharField(
                choices=[("descanso", "Descanso"), ("trabajo", "Trabajo")], max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="category",
            field=models.CharField(
                choices=[
                    ("Peluqueria", "Peluquería"),
                    ("Estetica", "Estética"),
                    ("Tratamientos", "Tratamientos"),
                ],
                max_length=12,
            ),
        ),
    ]
